#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/miaoruiyuan/GuanGong.git'
platform :ios, '8.0'

target 'GuanGong_Example' do
  #pod 'GuanGong', :path => '../'

  target 'GuanGong_Tests' do
    inherit! :search_paths

    pod 'GuanGong'
  end
end
